class Constants:
    flag_map = {
        'CHN': 'https://badmintonbites.com/wp-content/uploads/2020/01/china_flag.png',
        'KOR': 'https://badmintonbites.com/wp-content/uploads/2020/01/korea_flag.png',
        'DEN': 'https://badmintonbites.com/wp-content/uploads/2020/01/denmark_flag.png',
        'MAS': 'https://badmintonbites.com/wp-content/uploads/2020/01/malaysia_flag.png',
        'INA': 'https://badmintonbites.com/wp-content/uploads/2020/01/indonesia_flag.png',
        'JPN': 'https://badmintonbites.com/wp-content/uploads/2020/01/japan_flag.png',
        'TPE': 'https://badmintonbites.com/wp-content/uploads/2020/04/taiwan_flag.png',
        'THA': 'https://badmintonbites.com/wp-content/uploads/2020/04/thailand_flag.png',
        'RUS': 'https://badmintonbites.com/wp-content/uploads/2020/04/russia_flag.png',
        'ENG': 'https://badmintonbites.com/wp-content/uploads/2020/01/england_flag.png',
        'IND': 'https://badmintonbites.com/wp-content/uploads/2020/01/india_flag.png',
        'HKG': 'https://badmintonbites.com/wp-content/uploads/2020/04/hong_kong_flag.png',
        'NED': 'https://badmintonbites.com/wp-content/uploads/2020/04/netherlands_flag.png',
        'BUL': 'https://badmintonbites.com/wp-content/uploads/2020/04/bulgaria_flag.png',
        'POL': 'https://badmintonbites.com/wp-content/uploads/2020/04/poland_flag.png',
        'SIN': 'https://badmintonbites.com/wp-content/uploads/2020/04/singapore_flag.png',
        'GER': 'https://badmintonbites.com/wp-content/uploads/2020/04/germany_flag.png',
        'VIE': 'https://badmintonbites.com/wp-content/uploads/2020/04/vietnam_flag.png',
        'ESP': 'https://badmintonbites.com/wp-content/uploads/2020/01/spain_flag.png',
        'USA': 'https://badmintonbites.com/wp-content/uploads/2020/04/usa_flag.png',
        'CAN': 'https://badmintonbites.com/wp-content/uploads/2020/04/canada_flag.png',
    }